env:
  browser: true
  es2021: true
extends:
  - next
  - eslint:recommended
  - plugin:react/recommended
  - airbnb
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module
plugins:
  - react
rules:
  no-param-reassign: off
  "@next/next/no-img-element": off
  react/jsx-curly-brace-presence: off
  react/no-danger: off
  no-console: error
  no-underscore-dangle: off
  react/jsx-props-no-spreading: off
  react/destructuring-assignment: off
  react/prop-types: off
  react/react-in-jsx-scope: off
  react/jsx-filename-extension:
    - 1
    - extensions:
        - .js
        - .jsx
