---
- name: "Add font {{ font }}"
  file: 
    src: "{{ lookup('env', 'HOME') }}/app/Playbooks/.fonts/{{ font }}"
    dest: "{{ lookup('env', 'HOME') }}/.fonts/{{ font }}"
    force: yes
    state: link




